-- =========================================================================
-- PT Adi Sarana Armada, Tbk - SQL Database Setup Script for Supabase
-- =========================================================================
--
-- CARA PENGGUNAAN:
-- 1. Buka Dashboard Supabase Anda (https://supabase.com).
-- 2. Pilih project Anda, kemudian navigasi ke menu "SQL Editor" di panel kiri.
-- 3. Klik "+ New query" untuk membuat tab query baru.
-- 4. SALIN (Copy) seluruh isi file ini dan TEMPEL (Paste) ke editor tersebut.
-- 5. Klik tombol "Run" di kanan bawah untuk mengeksekusi script.
--
-- CATATAN ERROR SEBELUMNYA:
-- Error "syntax error at or near '{'" terjadi karena Anda memasukkan kode
-- TypeScript (frontend/React) ke dalam SQL Editor Supabase. SQL Editor
-- hanya mendukung sintaks SQL (PostgreSQL). File ini berisi perintah SQL
-- yang benar untuk membuat tabel-tabel database Anda.
-- =========================================================================

-- 1. PEMBUATAN TABEL PROFILES (PENGGUNA / STAF)
CREATE TABLE IF NOT EXISTS public.profiles (
    id text PRIMARY KEY,
    email text UNIQUE NOT NULL,
    full_name text NOT NULL,
    role text NOT NULL,
    branch text NOT NULL,
    password text DEFAULT 'password123',
    created_at timestamp with time zone DEFAULT now()
);

-- 2. PEMBUATAN TABEL BACKCHARGES (TRANSAKSI DENDA / PENAGIHAN)
CREATE TABLE IF NOT EXISTS public.backcharges (
    id text PRIMARY KEY,
    category text NOT NULL,
    branch text NOT NULL,
    no_bak text DEFAULT '-',
    no_spk text DEFAULT '-',
    no_sap text DEFAULT '-',
    customer_name text NOT NULL,
    license_plate text DEFAULT '-',
    value bigint NOT NULL DEFAULT 0,
    status_sap text DEFAULT 'N/A',
    status_confirm text DEFAULT 'Belum Konfirmasi',
    status_handover text DEFAULT 'Pending',
    no_invoice text DEFAULT '-',
    status_payment text DEFAULT 'Belum Bayar',
    created_by text NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    file_bak_url text,
    file_handover_aso_sales_url text,
    file_handover_sales_admin_url text
);

-- 3. PEMBUATAN TABEL ACTIVITY LOGS (LOG AKTIVITAS SISTEM)
CREATE TABLE IF NOT EXISTS public.activity_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp timestamp with time zone DEFAULT now(),
    transaction_id text NOT NULL,
    performed_by text NOT NULL,
    action_description text NOT NULL
);

-- 4. NONAKTIFKAN ROW LEVEL SECURITY (RLS) UNTUK KEPERLUAN INTERNAL CEPAT
-- Jika Anda ingin mengaktifkan RLS, buatlah policy SELECT/INSERT/UPDATE terlebih dahulu.
-- Menonaktifkan RLS memastikan aplikasi web Anda dapat langsung terhubung & sinkron.
ALTER TABLE public.profiles DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.backcharges DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.activity_logs DISABLE ROW LEVEL SECURITY;

-- 5. SEED DATA DEFAULT (AKUN DEMO DAN TRANSAKSI CONTOH)
-- Menambahkan data awal sehingga dashboard tidak kosong saat pertama kali dibuka.
INSERT INTO public.profiles (id, email, full_name, role, branch, password, created_at)
VALUES
    ('1', 'admin.pusat@company.id', 'Aris Munandar (HQ Admin)', 'Administrator', 'Nasional', 'password123', now()),
    ('2', 'aso.jkt@company.id', 'Hendra Wijaya (ASO Jkt)', 'ASO / Staff', 'Jakarta', 'password123', now()),
    ('3', 'sales.jkt@company.id', 'Dewi Lestari (Sales Jkt)', 'Sales / Sales Head', 'Jakarta', 'password123', now()),
    ('4', 'bro.sby@company.id', 'Bayu Saputra (BRO Sby)', 'BRO', 'Surabaya', 'password123', now()),
    ('5', 'admin.sby@company.id', 'Siti Rahma (Admin Sby)', 'Admin', 'Surabaya', 'password123', now()),
    ('6', 'aso.bdg@company.id', 'Budi Setiawan (ASO Bdg)', 'ASO / Staff', 'Bandung', 'password123', now()),
    ('7', 'sales.mdn@company.id', 'Rian Pratama (Sales Mdn)', 'Sales / Sales Head', 'Medan', 'password123', now())
ON CONFLICT (email) DO UPDATE 
SET 
    full_name = EXCLUDED.full_name,
    role = EXCLUDED.role,
    branch = EXCLUDED.branch,
    password = EXCLUDED.password;

INSERT INTO public.backcharges (
    id, category, branch, no_bak, no_spk, no_sap, customer_name, license_plate, value, 
    status_sap, status_confirm, status_handover, no_invoice, status_payment, created_by, 
    created_at, updated_at, file_bak_url, file_handover_aso_sales_url, file_handover_sales_admin_url
)
VALUES
    ('BC-2026-0001', 'Own Risk', 'Jakarta', 'BAK/2026/06/001', '-', 'SAP-OR-101', 'PT Carrefour Indonesia', 'B 9201 UBA', 4500000, 'Bill', 'Telah Dikonfirmasi', 'Diterima Admin', 'INV/2026/VI/011', 'Lunas', 'aso.jkt@company.id', now() - interval '3 days', now() - interval '3 days', 'dummy_pdf_file', 'dummy_photo_1', 'dummy_photo_2'),
    ('BC-2026-0002', 'Maintenance', 'Surabaya', 'BAK/2026/06/002', 'SPK-MAINT-202', '-', 'PT Unilever Indonesia', 'L 1827 CV', 1200000, 'N/A', 'Telah Dikonfirmasi', 'Diserahkan ke Admin', '-', 'Belum Bayar', 'bro.sby@company.id', now() - interval '1 day', now() - interval '1 day', 'dummy_pdf_file', null, null),
    ('BC-2026-0003', 'Ekspedisi', 'Bandung', '-', 'SPK-EXP-303', '-', 'PT Indofood CBP', '-', 8500000, 'N/A', 'Belum Konfirmasi', 'Pending', '-', 'Belum Bayar', 'aso.bdg@company.id', now(), now(), null, null, null)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.activity_logs (timestamp, transaction_id, performed_by, action_description)
VALUES
    (now() - interval '3 days', 'BC-2026-0001', 'aso.jkt@company.id', 'Membuat transaksi Backcharge baru kategori Own Risk di cabang Jakarta'),
    (now() - interval '2 days', 'BC-2026-0001', 'sales.jkt@company.id', 'Status Konfirmasi berubah dari "Belum Konfirmasi" menjadi "Telah Dikonfirmasi"'),
    (now() - interval '1 day', 'BC-2026-0002', 'bro.sby@company.id', 'Membuat transaksi Backcharge baru kategori Maintenance di cabang Surabaya')
ON CONFLICT DO NOTHING;

-- 6. [OPSIONAL] SINKRONISASI SUPABASE AUTH DENGAN PUBLIC.PROFILES
-- Script di bawah ini akan otomatis membuat profil di tabel 'profiles' ketika pengguna mendaftar lewat Supabase Auth.
-- Jalankan ini agar setiap kali user login lewat email auth, mereka punya entri profile secara otomatis.
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, email, full_name, role, branch, password, created_at)
  VALUES (
    new.id,
    new.email,
    COALESCE(new.raw_user_meta_data->>'full_name', split_part(new.email, '@', 1)),
    'ASO / Staff',
    'Jakarta',
    'password123',
    now()
  )
  ON CONFLICT (email) DO UPDATE
  SET id = EXCLUDED.id; -- Menghubungkan ID baru dari Auth
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Memicu fungsi handle_new_user setiap kali ada baris baru di tabel auth.users
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- 7. AKTIFKAN REALTME DARI DATABASE SUPABASE
-- Script ini akan menghapus dan membuat ulang publikasi 'supabase_realtime' untuk mendeteksi
-- insert, update, dan delete secara instan agar tombol lonceng Notifikasi Real-Time di aplikasi menyala otomatis.
BEGIN;
  DROP PUBLICATION IF EXISTS supabase_realtime CASCADE;
  CREATE PUBLICATION supabase_realtime FOR TABLE public.backcharges, public.profiles, public.activity_logs;
COMMIT;

